[platformio]
default_envs = uno_r4_wifi

[env:uno_r4_wifi]
platform = renesas-ra @ ^1.9.0
board = uno_r4_wifi
framework = arduino
monitor_speed = 115200
upload_protocol = sam-ba
lib_deps =
  adafruit/Adafruit AHTX0
  adafruit/Adafruit BMP280 Library
  adafruit/DHT sensor library
  adafruit/Adafruit Unified Sensor
  adafruit/RTClib
  bblanchon/ArduinoJson @ ^7.4.2
check_tool = cppcheck
check_flags =
  cppcheck: --enable=warning,style,performance,portability
