#pragma once

#include <Arduino.h>

static const char DashboardHtml[] PROGMEM = R"HTML(
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Cold-Chain Environmental Monitor</title>
<style>
:root{font-family:Inter,system-ui,-apple-system,sans-serif;color:#14213d;background:#f5f7fb}*{box-sizing:border-box}body{margin:0}.wrap{max-width:1180px;margin:auto;padding:18px}.top{display:flex;justify-content:space-between;gap:12px;align-items:center}.badge{padding:7px 12px;border-radius:999px;background:#e5e7eb;font-weight:700}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:12px;margin:16px 0}.card{background:white;border-radius:16px;padding:16px;box-shadow:0 4px 18px #17255412}.value{font-size:2rem;font-weight:800}.muted{color:#64748b}.row{display:flex;gap:10px;flex-wrap:wrap}button,input,select,textarea{font:inherit;border:1px solid #cbd5e1;border-radius:10px;padding:10px}button{background:#163f73;color:white;border:0;font-weight:700;cursor:pointer}button.secondary{background:#475569}button.danger{background:#b42318}form{display:grid;gap:10px}.two{display:grid;grid-template-columns:1fr 1fr;gap:10px}canvas{width:100%;height:260px;background:white;border-radius:12px}.events button{margin:4px}.hidden{display:none}.ok{color:#027a48}.warn{color:#b54708}.bad{color:#b42318}@media(max-width:650px){.two{grid-template-columns:1fr}.value{font-size:1.6rem}}</style></head>
<body><div class="wrap"><div class="top"><div><h1>Cold-Chain Environmental Monitor</h1><div class="muted">Educational environmental telemetry — not a certified compliance device</div></div><span id="state" class="badge">Connecting</span></div>
<section id="setup" class="card hidden"><h2>First-time security setup</h2><p>Create a private device hotspot password and dashboard administrator password.</p><form id="setupForm"><input name="apPassword" type="password" minlength="8" placeholder="Wi-Fi password (8+ characters)" required><input name="adminPassword" type="password" minlength="10" placeholder="Administrator password (10+ characters)" required><button>Save and restart</button></form></section>
<div class="grid"><div class="card"><div class="muted">DHT22 temperature (primary)</div><div id="dhtTemp" class="value">--</div><div id="dhtTempF" class="muted">--</div></div><div class="card"><div class="muted">DHT22 humidity</div><div id="dhtRh" class="value">--</div></div><div class="card"><div class="muted">BMP280 temperature</div><div id="bmpTemp" class="value">--</div></div><div class="card"><div class="muted">BMP280 pressure</div><div id="pressure" class="value">--</div></div><div class="card"><div class="muted">AHT20 temperature (optional)</div><div id="ahtTemp" class="value">--</div><div id="ahtTempF" class="muted">--</div></div><div class="card"><div class="muted">AHT20 humidity (optional)</div><div id="ahtRh" class="value">--</div></div></div>
<div class="grid"><div class="card"><h3>Sensor agreement</h3><div>Temperature difference: <b id="tempDiff">--</b></div><div>Humidity difference: <b id="rhDiff">--</b></div><div id="quality" class="muted">Waiting for readings</div></div><div class="card"><h3>Run</h3><div id="runInfo">No active run</div><div class="row" style="margin-top:10px"><a href="/api/download/data"><button type="button">CSV</button></a><a href="/api/download/events"><button type="button" class="secondary">Events</button></a><a href="/api/download/metadata"><button type="button" class="secondary">Metadata</button></a></div></div><div class="card"><h3>Storage</h3><div id="storage">--</div><div class="muted">Files are stored in the UNO R4 WiFi connectivity module. Download each run after testing.</div></div></div>
<div class="card"><canvas id="chart" width="1000" height="260"></canvas></div>
<div class="grid"><div class="card"><h2>Start experiment</h2><form id="runForm"><div class="two"><input name="trialId" placeholder="Trial ID" required><input name="researcher" value="Moksh Joshi" placeholder="Researcher" required></div><div class="two"><select name="experimentType"><option>Stable baseline</option><option>Short door opening</option><option>Repeated door openings</option><option>Cooling interruption</option><option>Sensor placement comparison</option><option>Facility observation</option></select><select name="sensorLocation"><option>Center</option><option>Door-adjacent</option><option>Top</option><option>Bottom</option><option>Wall-adjacent</option><option>Vent-adjacent</option><option>Room ambient</option></select></div><div class="two"><input name="enclosureType" placeholder="Enclosure type"><input name="operatingCondition" placeholder="Operating condition"></div><label><input type="checkbox" name="thresholdEnabled" checked> Use configured study range</label><div class="two"><input name="lowerThresholdC" type="number" step="0.1" value="2"><input name="upperThresholdC" type="number" step="0.1" value="8"></div><div class="two"><input name="sampleIntervalSeconds" type="number" min="2" value="10"><input name="plannedDurationMinutes" type="number" min="0" value="60"></div><textarea name="notes" placeholder="Run notes"></textarea><button>Start run</button></form><button id="stopBtn" class="danger" style="margin-top:10px">Stop active run</button></div>
<div class="card"><h2>Record event</h2><div class="events" id="eventButtons"></div><div class="row"><input id="eventNote" style="flex:1" placeholder="Optional note or reference thermometer reading"><button id="noteBtn">Record note</button></div></div></div>
<script>
const events=['Door opened','Door closed','Cooling interrupted','Cooling restored','Sensor moved','Cold pack added','Cold pack removed','Experiment phase changed','Reference thermometer reading','Unexpected event'];
const hist=[];const fmt=(v,n=1)=>Number.isFinite(v)?v.toFixed(n):'--';
async function post(url,obj){const body=new URLSearchParams(obj);const r=await fetch(url,{method:'POST',body});if(!r.ok)throw new Error(await r.text());return r.text()}
function chart(){const c=document.getElementById('chart'),x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);x.strokeStyle='#d0d5dd';for(let i=1;i<5;i++){x.beginPath();x.moveTo(0,i*c.height/5);x.lineTo(c.width,i*c.height/5);x.stroke()}if(hist.length<2)return;const vals=hist.flatMap(p=>[p.a,p.d]).filter(Number.isFinite);if(!vals.length)return;let min=Math.min(...vals)-1,max=Math.max(...vals)+1;function line(k,color){x.strokeStyle=color;x.lineWidth=3;x.beginPath();let started=false;hist.forEach((p,i)=>{if(!Number.isFinite(p[k])){started=false;return}const px=i*c.width/(hist.length-1),py=c.height-(p[k]-min)*c.height/(max-min);started?x.lineTo(px,py):x.moveTo(px,py);started=true});x.stroke()}line('a','#2563eb');line('d','#ea580c')}
function setState(s){const e=document.getElementById('state');e.textContent=s;e.style.background=s.includes('ERROR')?'#fee4e2':s.includes('EXCURSION')?'#fecdca':s.includes('WARNING')||s.includes('PENDING')?'#fef0c7':'#dcfae6'}
async function refresh(){try{const r=await fetch('/api/status');if(r.status===401)return;const j=await r.json();document.getElementById('setup').classList.toggle('hidden',!j.setupMode);setState(j.state);ahtTemp.textContent=fmt(j.reading.ahtTemperatureC)+' °C';ahtTempF.textContent=fmt(j.reading.ahtTemperatureC*9/5+32)+' °F';ahtRh.textContent=fmt(j.reading.ahtHumidityPct)+' %';dhtTemp.textContent=fmt(j.reading.dhtTemperatureC)+' °C';dhtTempF.textContent=fmt(j.reading.dhtTemperatureC*9/5+32)+' °F';dhtRh.textContent=fmt(j.reading.dhtHumidityPct)+' %';bmpTemp.textContent=fmt(j.reading.bmpTemperatureC)+' °C';pressure.textContent=fmt(j.reading.bmpPressureHpa)+' hPa';tempDiff.textContent=fmt(j.quality.temperatureDifferenceC)+' °C';rhDiff.textContent=fmt(j.quality.humidityDifferencePct)+' % RH';quality.textContent=j.quality.message;runInfo.textContent=j.run.active?`${j.run.trialId} • ${j.run.sampleCount} samples • ${j.run.excursionCount} excursions`:'No active run';storage.textContent=`${j.storage.runBytesWritten.toLocaleString()} bytes written this run`;if(Number.isFinite(j.reading.dhtTemperatureC)){hist.push({a:j.reading.ahtTemperatureC,d:j.reading.dhtTemperatureC});if(hist.length>180)hist.shift();chart()}}catch(e){setState('DISCONNECTED')}}
setupForm.onsubmit=async e=>{e.preventDefault();await post('/api/setup',Object.fromEntries(new FormData(e.target)));alert('Saved. Reconnect after restart.')};
runForm.onsubmit=async e=>{e.preventDefault();await post('/api/run/start',Object.fromEntries(new FormData(e.target)));await refresh()};stopBtn.onclick=()=>post('/api/run/stop',{}).then(refresh);noteBtn.onclick=()=>post('/api/event',{type:'General note',note:eventNote.value}).then(()=>eventNote.value='');
events.forEach(name=>{const b=document.createElement('button');b.textContent=name;b.onclick=()=>post('/api/event',{type:name,note:eventNote.value}).then(()=>eventNote.value='');eventButtons.appendChild(b)});setInterval(refresh,2000);refresh();
</script></body></html>
)HTML";
